# Generated by Django 5.2 on 2026-09-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('folder', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '图片表',
                'db_table': 'com_img',
            },
        ),
    ]
