# Generated by Django 5.2 on 2026-09-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10, unique=True, verbose_name='图书编号')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='图书名字')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='图书价格')),
                ('status', models.BooleanField(default=False, verbose_name='借阅状态')),
                ('book_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.booktype', verbose_name='图书类型')),
            ],
            options={
                'verbose_name': '图书表',
                'db_table': 'book',
            },
        ),
    ]
